### ISSUE TITLE
lightning -> électro

### ISSUE THREAD

**Issue by brunobord** [brunobord/ghostlines-fr#1]
le terme "foudre" passe mal.
- lightning-hook : électrogriffe
- Lightning-web: électrotoile
- Lightning-Oil : Huile d'éclair ?

**Comment by jazzynico** [comment]
Électro n'est pas mal, en effet.
Pour lightning-web, j'avais tout d'abord pensé à électro-fillet, mais vu qu'il s'agit d'une araignée, tu as sans doute raison.
Pour lightning-oil, électro-graisse ?

**Comment by brunobord** [comment]
Suggestion par email:

> huile luminique ?

**Comment by jazzynico** [comment]
Si l'on tient compte de l'effet attendu de l'huile en question (à savoir détruire l'essence de l'esprit), il faudrait chercher un sens plus destructeur, ou purificateur. Huile foudroyante ou fulgurante (si on est pressé), ou plus poétiquement (et pour un processus plus lent) huile d'évanescence.
J'ai aussi cherché dans l’étymologie des deux parties, mais ça ne me semble pas tout à fait convainquant (de la photo-oléine, du fulguroleum ?).

**Comment by brunobord** [comment]
je me laisse le week-end pour y réfléchir

**Comment by brunobord** [comment]
Suggestion:
- lightning-hook : électrogriffe
- Lightning-web: électrotoile
- Lightning-Oil : électrhuile
