### ISSUE TITLE
Handicaps sur "Horreurs" non traduites

### ISSUE THREAD

**Issue by brunobord** [brunobord/ghostlines-fr#16]
Dû au fait que le texte est en arc de cercle (et que je n'ai pas trouvé comment faire avec les moyens du bord).

(note : j'avais eu de la chance que Force et Finesse se traduisent pareil)

**Comment by jazzynico** [comment]
Si tu me laisse un peu de temps (disons jusqu'au milieu de la semaine prochaine), je peux m'en charger.

**Comment by brunobord** [comment]
un Google-Plusien l'a très généreusement fait dans l'après-midi.
ref: https://plus.google.com/u/0/102964384717941736128/posts/MN6k9ueCjKG
