### ISSUE TITLE
Request for file removal: ACaslonPro-Bold.otf

### ISSUE THREAD

**Issue by miguelsousa** [brunobord/ghostlines-fr#19]
When using http://www.getthefont.com/, I found your font file [ACaslonPro-Bold.otf](http://github.com/brunobord/ghostlines-fr/blob/0f2ea50676f664a6f8d71574cbe5f22209c86a00/css/fonts/ACaslonPro-Bold.otf), uploaded in this repository. I believe that this file was uploaded here by mistake, because its license does not allow distribution through a public website.

I would like to kindly ask you to remove this font file from the repository.

Kind regards,

**Comment by brunobord** [comment]
Hi,

I'm deeply sorry about this mistake ; I should have paid attention to this license.
I'll remove all occurrences of this font as soon as possible.

Regards,

**Comment by brunobord** [comment]
... and the others.

**Comment by brunobord** [comment]
just to be sure: the font is in the repository *history*, so it'll be accessible via the git log. Do you want me to remove it from the history also? (I can't say I'm happy with this, it'll require me to completely rebase from the very early stages of my history, and scratch my tags, etc.)

**Comment by brunobord** [comment]
right. so I've scratched everything, the .OTF files are not available in any history anymore.

I apologise again for the mess.

**Comment by miguelsousa** [comment]
Much appreciated. Thanks.
