### ISSUE TITLE
Bulls

### ISSUE THREAD

**Issue by brunobord** [brunobord/ghostlines-fr#3]
En argot de Philadelphie, les gens chargés de virer les clochards des trains sont appelés "bulls" ; c'est probablement ce terme qui a servi d'origine au terme utilisé dans Ghost Lines.

Suggestions de traduction ?

**Comment by brunobord** [comment]
Suggestions (par email) :

> mercenaires, commandos,

Je ne suis pas d'accord avec ce terme, qui sous-entend l'appât du gain. les Bulls sont chargés de la sécurité des trains, c'est un peu plus comme des surveillants, des mâtons, mais sans la connotation carcérale.

**Comment by brunobord** [comment]
- Gaillards ?
- Brutes ?
- Cerbères ?

ne pas oublier que la traduction employée doit être associée avec "Maître" puisqu'il existe des "Master Bulls"

**Comment by brunobord** [comment]
suggestion par email: Shérif.

(un peu connoté, mais bon)

**Comment by brunobord** [comment]
suggestions par email:
- Agents anti-spectres
- spectrogardiens
- Régulateurs

**Comment by brunobord** [comment]
j'aime bien "Régulateurs". même s'il manque la notion de "brute" qui se dégage du terme original "Bull"

**Comment by jazzynico** [comment]
Sentinelle, veilleur, ou dans un registre plus technique, mainteneur. Mais là encore, le côté brute ne ressort pas trop.
Cogneur se rapproche plus du sens de bull (maître cogneur, ça sonne pas trop mal non plus).

Sinon, j'aime bien régulateur aussi.

**Comment by jazzynico** [comment]
Quoique si l'on regarde dans l'argot (http://onlineslangdictionary.com/meaning-definition-of/bull), bull désigne aussi le maton. Surveillant pourrait donc tout aussi bien faire l'affaire.

**Comment by brunobord** [comment]
pour être sûr, j'enverrai un email à John Harper, mais après, il faudra trancher.

**Comment by brunobord** [comment]
échange de mail avec John Harper lui-même. Je lui demandais de m'éclairer sur les origines de l'argot "bull":

> Yes, you're right, the slang term refers to the animal. I think it would be good to use an archaic French equivalent for authority figure. Maybe you have a slang term for city watchmen or jailors? "Bull" sounds old-timey to English-speakers, so something like that would be good.

**Comment by brunobord** [comment]
le soucis, c'est que l'animal qui représente le policier, c'est "Poulet". Je vois pas trop ça en remplacement de "Bull". Dans mon état d'esprit, ce qui colle le mieux reste encore "Cerbère", pour plusieurs raisons :
- animal mythologique,
- représente le gardien, celui qui protège quelque chose
- a la connotation "inquiétant"
- peut se "marier" avec "Maître" et "Apprenti" sans problème.

et en sus, durant les scènes jouées, on pourra même se fendre d'un petit surnom : "Cerb'"
