### ISSUE TITLE
Move

### ISSUE THREAD

**Issue by brunobord** [brunobord/ghostlines-fr#5]
Comment traduire "Move". C'est le mot consacré pour "tout ce qui se passe entre un dialogue et un jet" et "tout ce qui se passe après un jet partiellement réussi ou échoué".
- Mouvement ?
- Action ? 
- Acte ? [j'ai entendu ce terme ici](http://radio-roliste.net/2013/09/05/radio-roliste-27-punch-party-3/)

Avis ?

**Comment by ghost** [comment]
Je dirais "Déroulement". Mais pas convaincu.

**Comment by zyegfryed** [comment]
Action ou Mouvement me semble bien.
My 2 cents.

**Comment by mrjmad** [comment]
Mouvement me semble cool.

**Comment by brunobord** [comment]
@segle : ça sonne mal "you make a Move" / "the GM makes a Move" - je vois pas trop comment dire avec "Déroulement"

**Comment by jazzynico** [comment]
Difficile de trouver quelque-chose qui colle aussi bien avec : 
1. Tout ce qui se passe entre un dialogue et un jet.
2. Tout ce qui se passe après un jet partiellement réussi ou échoué.

Sauf à traduire les deux avec deux mots différents. Pour le 1, ce pourrait être décision, pour le 2 conséquence.

Il y aurait aussi coup, mais ce serait plus approprié aux jeux de plateau il me semble.
