### ISSUE TITLE
Flasque-à-esprit

### ISSUE THREAD

**Issue by jazzynico** [brunobord/ghostlines-fr#8]
De même que nous utilisons Puits-à-esprit (ou peut-être vaudrait-il mieux Puits-à-esprits), ne pourrions nous pas choisir Flasque-à-esprit (a priori un seul par flasque, ici). D'autant que Flasque-esprit laisse penser que la flasque est elle-même un esprit, alors qu'elle n'en est que le contenant.

**Comment by brunobord** [comment]
tu as sans doute raison.
